# Generated by Django 5.0.6 on 2024-05-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memebers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=255, null=True, verbose_name='shopname')),
                ('ownersname', models.CharField(max_length=255, null=True, verbose_name='ownersname')),
            ],
        ),
    ]
