# Generated by Django 5.0.6 on 2024-05-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memebers',
            name='joined_date',
            field=models.DateField(null=True, verbose_name='joined_date'),
        ),
        migrations.AddField(
            model_name='memebers',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='phone'),
        ),
    ]
