# Generated by Django 5.0.6 on 2024-05-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_memebers_joined_date_memebers_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='memebers',
            name='bio',
            field=models.CharField(max_length=255, null=True, verbose_name='bio'),
        ),
    ]
