# Generated by Django 5.1.3 on 2025-01-22 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_memebers_bio_alter_memebers_joined_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
    ]
