# Generated by Django 5.1.3 on 2025-01-23 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_price_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='lga',
            field=models.CharField(blank=True, max_length=100, verbose_name='Local Government Area'),
        ),
        migrations.AddField(
            model_name='price',
            name='market_store_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='market or store name'),
        ),
        migrations.AddField(
            model_name='price',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='price',
            name='author',
            field=models.ForeignKey(default=models.F('user'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
