# Generated by Django 5.1.3 on 2025-01-24 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_price_lga_price_market_store_name_price_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='price',
            name='lga',
            field=models.CharField(blank=True, max_length=100, verbose_name='local government area'),
        ),
        migrations.AlterField(
            model_name='price',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='state'),
        ),
    ]
